load assembly.maude

(mod TEST is
  pr SEMANTICS .

  op il : -> InsList .
  eq il =
      'test
              addiu   sp,sp,32
              sw      ra,28(sp)
              sw      s8,24(sp)
              move    s8,sp
              lbu     v0,40(gp)
              andi    v0,v0,255
              beqz    v0, 'test2
              nop
              sb      zero,40(gp)
      'test2  lbu     v0,12(gp)
              addiu   v0,v0,1
              andi    v0,v0,255
  .

  op test : -> System .
  eq test = [il | mtReg | mtMem | 0] .
endm)

***(red il .)

(flat test with IndexIns .)

eof

Flatten list 0 : addiu sp,sp,32
next
1 : sw ra,28(sp)
next
2 : sw s8,24(sp)
next
3 : move s8,sp
next
4 : lbu v0,40(gp)
next
5 : andi v0,v0,255
next
6 : beqz v0,'test2
next
7 : nop
next
8 : sb zero,40(gp)
next
9 : lbu v0,12(gp)
next
10 : addiu v0,v0,1
next
11 : andi v0,v0,255
next