load wfe.maude

(mod EXAMPLE is
 pr EVALUATION-WHILE .

 op myFunsDeb : -> FunSet .
 eq myFunsDeb = 'Main(nv){
                       a := 1 ;
                       Call 'Foo(a)
                }
                'Foo ( x ) {
                       y := x +. (z +. 2) ;
                       x := 'hola
                } .

endm)

(set side-effect sorts ESt RWBUF .)

(set context-update rules CallF .)

(islice Statement with defs myFunsDeb wrt a .)